### ISSUE TITLE
Watermark size

### ISSUE THREAD

**Issue by OlegKn** [mcsyko/HiddenWatermark#1]
Hi,

Great method! A couple of questions, though:

1) Why 32x32px max? Are there any physical limits with regards to image quality?
2) What's the max resolution that your method supports?

Thanks

**Comment by mchall** [comment]
To support resistance to scaling (and for performance) a 512x512 watermark image is generated and then merged with an image for watermarking. This 512x512 image has two levels of DWT applied to it, and so the actual working space is 128x128, which is then divided into 4x4 blocks for DCT - which is basically 32x32 blocks for embedding the watermark. 
You could alter the code to support larger watermarks but this will have a negative impact on performance. It could be done by applying only one level of DWT (which would give a 64x64 maximum), or a larger watermark image to be even larger.

The method will support watermarking any image size, it'll just be slower obviously. By default cropping support is limited to 1024x768, but there's an overload if you want to support extra common image dimensions.
