### ISSUE TITLE
Suggestion with regards to 'Hidden'

### ISSUE THREAD

**Issue by OlegKn** [mcsyko/HiddenWatermark#2]
Hi again!

I've been running a lot tests with regards to the robustness of your algorithm - it works great against most real-life attacks, although there are certain hiccups. The most notable is that it's not really 'hidden' when it comes to more or less monotone backgrounds. Here is what i mean:

https://drive.google.com/file/d/0B6WJ-pOJkhy2MnQycEJBM2Nfak0/view?usp=sharing (watermarked image)
https://drive.google.com/file/d/0B6WJ-pOJkhy2M3FRSC1ZR3hPLVU/view?usp=sharing (original image)

I haven't been able to find a way around this, though :(

**Comment by mchall** [comment]
The algorithm is more suited for natural scene images, but I fixed it to not embed the watermark in the background of these sorts of images to maintain invisibility. But the recovered watermark might be poor depending on how much background there is to the image:

![recoveredwatermark](https://cloud.githubusercontent.com/assets/3825339/8001230/fe04ec2e-0b63-11e5-8271-cb4d7b792fbd.jpg)

**Comment by OlegKn** [comment]
Can we talk via email? I've got some more test results that came out that can dramatically improve the algorithm (one of them is that it's very margin-heavy).

**Comment by mchall** [comment]
Sure. 
mcsyko [@] gmail.com
