### ISSUE TITLE
Can you tell me an academic paper for the blind watermarking technique used in this project?

### ISSUE THREAD

**Issue by ndb796** [mcsyko/HiddenWatermark#6]
Hi! Thank you for sharing a good project :)
Is there a python implementation version of this project?
Or can you tell me an academic paper for the blind watermarking technique used in this project?

**Comment by mchall** [comment]
Sorry, it's only loosely based on some academic papers. None of them had the kind of results or performance I was happy with, so it's not based on any specific paper. 
There's no python implementation, sorry.

**Comment by ndb796** [comment]
Thank you for your answer :)
